### ISSUE TITLE
Example code fails with KeyError: 'SETf426042f_f4c5_4fc7_9fa8_a61fd787ac16'

### ISSUE THREAD

**Issue by amipy** [fossilfree/numerous#64]
When using the example code provided in the README file, the following error is thrown after numerous reports 'variables sorted':

`

Traceback (most recent call last):
    File "C:\Users\alexi\Desktop\numerous-master\example.py", line 5, in <module>
      model.Model(OscillatorSystem('system')),
    File "C:\Users\alexi\Desktop\numerous-master\numerous\engine\model\model.py", line 166, in __init__
      self.assemble()
    File "C:\Users\alexi\Desktop\numerous-master\numerous\engine\model\model.py", line 312, in assemble
      tmp_vars = self.mappings_graph.create_assignments(self.variables)
    File "C:\Users\alexi\Desktop\numerous-master\numerous\engine\model\graph_representation\mappings_graph.py", line 108, in create_assignments
      tmp_label = sv.tag + variables[str(self.key_map[va])].path.primary_path + '_tmp'
KeyError: 'SETf426042f_f4c5_4fc7_9fa8_a61fd787ac16'
`
The key causing the error changes every run, but always has the SET prefix.

**Comment by artem-chupryna** [comment]
Seems like += assignment stoped working for set variables. We need a test covering += for set variables in tests/set_variables_test
